In [43]:
from io import StringIO

import pandas as pd
import requests

# URL to fetch swimming world records data.
URL = "https://en.wikipedia.org/wiki/List_of_world_records_in_swimming"

headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"
}

response = requests.get(URL, headers=headers)

tables = pd.read_html(StringIO(response.text))

len(tables)

21

In [60]:
df = tables[4] # Complete dataframe
# df.head() # First 5 rows
# df.tail() # Last 5 rows

df

# 0 - LC Men
# 1 - LC Women
# 3 - SC Men
# 4 - SC Women

,Event,Time,Unnamed: 2,Name,Nationality,Date,Meet,Location,Ref
0,50m freestyle,22.83,NaN,Gretchen Walsh,United States,15 December 2024,World Championships,"Budapest, Hungary",[126][127]
1,100m freestyle,49.93,NaN,Kate Douglass,United States,25 October 2025,World Cup,"Toronto, Canada",[128]
2,200m freestyle,1:49.36,NaN,Mollie O'Callaghan,Australia,24 October 2025,World Cup,"Toronto, Canada",[129]
3,400m freestyle,3:50.25,NaN,Summer McIntosh,Canada,10 December 2024,World Championships,"Budapest, Hungary",[130][131]
4,800m freestyle,7:54.00,NaN,Lani Pallister,Australia,25 October 2025,World Cup,"Toronto, Canada",[132][133]
5,1500m freestyle,15:08.24,NaN,Katie Ledecky,United States,29 October 2022,World Cup,"Toronto, Canada",[134][135]
6,50m backstroke,25.23,NaN,Regan Smith,United States,13 December 2024,World Championships,"Budapest, Hungary",[136][137]
7,100m backstroke,54.02,r =,Regan Smith,United States,15 December 2024,World Championships,"Budapest, Hungary",[138][139]
8,100m backstroke,54.02,=,Regan Smith,United States,18 October 2025,World Cup,"Westmont, United States",[140]
9,200m backstroke,1:57.33,NaN,Kaylee McKeown,Australia,25 October 2025,World Cup,"Toronto, Canada",[141]
10,50m breaststroke,28.37,sf,Rūta Meilutytė,Lithuania,17 December 2022,World Championships,"Melbourne, Australia",[142]
11,100m breaststroke,1:02.36,=,Rūta Meilutytė,Lithuania,12 October 2013,World Cup,"Moscow, Russia",[143]
12,100m breaststroke,1:02.36,=,Alia Atkinson,Jamaica,6 December 2014,World Championships,"Doha, Qatar",[144][145]
13,100m breaststroke,1:02.36,=,Alia Atkinson,Jamaica,26 August 2016,World Cup,"Chartres, France",[146]
14,200m breaststroke,2:12.50,NaN,Kate Douglass,United States,13 December 2024,World Championships,"Budapest, Hungary",[147][148]
15,50m butterfly,23.72,NaN,Gretchen Walsh,United States,11 October 2025,World Cup,"Carmel, United States",[149]
16,100m butterfly,52.71,NaN,Gretchen Walsh,United States,14 December 2024,World Championships,"Budapest, Hungary",[150][151]
17,200m butterfly,1:59.32,NaN,Summer McIntosh,Canada,12 December 2024,World Championships,"Budapest, Hungary",[152][153]
18,100m individual medley,55.11,NaN,Gretchen Walsh,United States,13 December 2024,World Championships,"Budapest, Hungary",[154][155]
19,200m individual medley,2:01.63,NaN,Kate Douglass,United States,10 December 2024,World Championships,"Budapest, Hungary",[156][157]
20,400m individual medley,4:15.48,NaN,Summer McIntosh,Canada,14 December 2024,World Championships,"Budapest, Hungary",[158][159]
21,4 × 50 m freestyle relay,1:32.50,tt,Ranomi Kromowidjojo (23.05)Maaike de Waard (23...,Netherlands,12 December 2020,Wouda Cup,"Eindhoven, Netherlands",[160]
22,4 × 100 m freestyle relay,3:25.01,NaN,Kate Douglass (50.95)Katharine Berkoff (51.38)...,United States,10 December 2024,World Championships,"Budapest, Hungary",[161][162]
23,4 × 200 m freestyle relay,7:30.13,NaN,Alex Walsh (1:53.25)Paige Madden (1:53.18)Kati...,United States,12 December 2024,World Championships,"Budapest, Hungary",[163][164]
24,4 × 50 m medley relay,1:42.35,NaN,Mollie O'Callaghan (25.49)Chelsea Hodges (29.1...,Australia,17 December 2022,World Championships,"Melbourne, Australia",[165]
25,4 × 100 m medley relay,3:40.41,NaN,Regan Smith (54.02)Lilly King (1:03.02)Gretche...,United States,15 December 2024,World Championships,"Budapest, Hungary",[138][166]

In [45]:
df = df[["Event", "Time", "Name", "Nationality", "Date"]]

In [47]:
df.tail()

,Event,Time,Name,Nationality,Date
15,200m individual medley,1:52.69,Léon Marchand,France,30 July 2025
16,400m individual medley,4:02.50,Léon Marchand,France,23 July 2023
17,4 × 100 m freestyle relay,3:08.24,Michael Phelps (47.51)Garrett Weber-Gale (47.0...,United States,11 August 2008
18,4 × 200 m freestyle relay,6:58.55,Michael Phelps (1:44.49)Ricky Berens (1:44.13)...,United States,31 July 2009
19,4 × 100 m medley relay,3:26.78,Ryan Murphy (52.31)Michael Andrew (58.49)Caele...,United States,1 August 2021

In [48]:
df[df["Event"].str.contains("relay")]

,Event,Time,Name,Nationality,Date
17,4 × 100 m freestyle relay,3:08.24,Michael Phelps (47.51)Garrett Weber-Gale (47.0...,United States,11 August 2008
18,4 × 200 m freestyle relay,6:58.55,Michael Phelps (1:44.49)Ricky Berens (1:44.13)...,United States,31 July 2009
19,4 × 100 m medley relay,3:26.78,Ryan Murphy (52.31)Michael Andrew (58.49)Caele...,United States,1 August 2021

In [49]:
df[~df["Event"].str.contains("relay")]

,Event,Time,Name,Nationality,Date
0,50m freestyle,20.88,Cameron McEvoy,Australia,20 March 2026
1,100m freestyle,46.40,Pan Zhanle,China,31 July 2024
2,200m freestyle,1:42.00,Paul Biedermann,Germany,28 July 2009
3,400m freestyle,3:39.96,Lukas Märtens,Germany,12 April 2025
4,800m freestyle,7:32.12,Zhang Lin,China,29 July 2009
5,1500m freestyle,14:26.79,Johannes Liebmann,Germany,15 August 2026
6,50m backstroke,23.55,Kliment Kolesnikov,Russia,27 July 2023
7,100m backstroke,51.60,Thomas Ceccon,Italy,20 June 2022
8,200m backstroke,1:51.92,Aaron Peirsol,United States,31 July 2009
9,50m breaststroke,25.95,Adam Peaty,Great Britain,25 July 2017
10,100m breaststroke,56.88,Adam Peaty,Great Britain,21 July 2019
11,200m breaststroke,2:05.48,Qin Haiyang,China,28 July 2023
12,50m butterfly,22.27,Andriy Govorov,Ukraine,1 July 2018
13,100m butterfly,49.45,Caeleb Dressel,United States,31 July 2021
14,200m butterfly,1:50.34,Kristóf Milák,Hungary,21 June 2022
15,200m individual medley,1:52.69,Léon Marchand,France,30 July 2025
16,400m individual medley,4:02.50,Léon Marchand,France,23 July 2023

In [50]:
df = df[~df["Event"].str.contains("relay")]
df

,Event,Time,Name,Nationality,Date
0,50m freestyle,20.88,Cameron McEvoy,Australia,20 March 2026
1,100m freestyle,46.40,Pan Zhanle,China,31 July 2024
2,200m freestyle,1:42.00,Paul Biedermann,Germany,28 July 2009
3,400m freestyle,3:39.96,Lukas Märtens,Germany,12 April 2025
4,800m freestyle,7:32.12,Zhang Lin,China,29 July 2009
5,1500m freestyle,14:26.79,Johannes Liebmann,Germany,15 August 2026
6,50m backstroke,23.55,Kliment Kolesnikov,Russia,27 July 2023
7,100m backstroke,51.60,Thomas Ceccon,Italy,20 June 2022
8,200m backstroke,1:51.92,Aaron Peirsol,United States,31 July 2009
9,50m breaststroke,25.95,Adam Peaty,Great Britain,25 July 2017
10,100m breaststroke,56.88,Adam Peaty,Great Britain,21 July 2019
11,200m breaststroke,2:05.48,Qin Haiyang,China,28 July 2023
12,50m butterfly,22.27,Andriy Govorov,Ukraine,1 July 2018
13,100m butterfly,49.45,Caeleb Dressel,United States,31 July 2021
14,200m butterfly,1:50.34,Kristóf Milák,Hungary,21 June 2022
15,200m individual medley,1:52.69,Léon Marchand,France,30 July 2025
16,400m individual medley,4:02.50,Léon Marchand,France,23 July 2023

In [52]:
df = df.set_index("Event")
df

,Time,Name,Nationality,Date
Event,,,,
50m freestyle,20.88,Cameron McEvoy,Australia,20 March 2026
100m freestyle,46.40,Pan Zhanle,China,31 July 2024
200m freestyle,1:42.00,Paul Biedermann,Germany,28 July 2009
400m freestyle,3:39.96,Lukas Märtens,Germany,12 April 2025
800m freestyle,7:32.12,Zhang Lin,China,29 July 2009
1500m freestyle,14:26.79,Johannes Liebmann,Germany,15 August 2026
50m backstroke,23.55,Kliment Kolesnikov,Russia,27 July 2023
100m backstroke,51.60,Thomas Ceccon,Italy,20 June 2022
200m backstroke,1:51.92,Aaron Peirsol,United States,31 July 2009
50m breaststroke,25.95,Adam Peaty,Great Britain,25 July 2017
100m breaststroke,56.88,Adam Peaty,Great Britain,21 July 2019
200m breaststroke,2:05.48,Qin Haiyang,China,28 July 2023
50m butterfly,22.27,Andriy Govorov,Ukraine,1 July 2018
100m butterfly,49.45,Caeleb Dressel,United States,31 July 2021
200m butterfly,1:50.34,Kristóf Milák,Hungary,21 June 2022
200m individual medley,1:52.69,Léon Marchand,France,30 July 2025
400m individual medley,4:02.50,Léon Marchand,France,23 July 2023

In [54]:
df.to_dict()

{'Time': {'50m freestyle': '20.88',
  '100m freestyle': '46.40',
  '200m freestyle': '1:42.00',
  '400m freestyle': '3:39.96',
  '800m freestyle': '7:32.12',
  '1500m freestyle': '14:26.79',
  '50m backstroke': '23.55',
  '100m backstroke': '51.60',
  '200m backstroke': '1:51.92',
  '50m breaststroke': '25.95',
  '100m breaststroke': '56.88',
  '200m breaststroke': '2:05.48',
  '50m butterfly': '22.27',
  '100m butterfly': '49.45',
  '200m butterfly': '1:50.34',
  '200m individual medley': '1:52.69',
  '400m individual medley': '4:02.50'},
 'Name': {'50m freestyle': 'Cameron McEvoy',
  '100m freestyle': 'Pan Zhanle',
  '200m freestyle': 'Paul Biedermann',
  '400m freestyle': 'Lukas Märtens',
  '800m freestyle': 'Zhang Lin',
  '1500m freestyle': 'Johannes Liebmann',
  '50m backstroke': 'Kliment Kolesnikov',
  '100m backstroke': 'Thomas Ceccon',
  '200m backstroke': 'Aaron Peirsol',
  '50m breaststroke': 'Adam Peaty',
  '100m breaststroke': 'Adam Peaty',
  '200m breaststroke': 'Qin Haiyang',
  '50m butterfly': 'Andriy Govorov',
  '100m butterfly': 'Caeleb Dressel',
  '200m butterfly': 'Kristóf Milák',
  '200m individual medley': 'Léon Marchand',
  '400m individual medley': 'Léon Marchand'},
 'Nationality': {'50m freestyle': 'Australia',
  '100m freestyle': 'China',
  '200m freestyle': 'Germany',
  '400m freestyle': 'Germany',
  '800m freestyle': 'China',
  '1500m freestyle': 'Germany',
  '50m backstroke': 'Russia',
  '100m backstroke': 'Italy',
  '200m backstroke': 'United States',
  '50m breaststroke': 'Great Britain',
  '100m breaststroke': 'Great Britain',
  '200m breaststroke': 'China',
  '50m butterfly': 'Ukraine',
  '100m butterfly': 'United States',
  '200m butterfly': 'Hungary',
  '200m individual medley': 'France',
  '400m individual medley': 'France'},
 'Date': {'50m freestyle': '20 March 2026',
  '100m freestyle': '31 July 2024',
  '200m freestyle': '28 July 2009',
  '400m freestyle': '12 April 2025',
  '800m freestyle': '29 July 2009',
  '1500m freestyle': '15 August 2026',
  '50m backstroke': '27 July 2023',
  '100m backstroke': '20 June 2022',
  '200m backstroke': '31 July 2009',
  '50m breaststroke': '25 July 2017',
  '100m breaststroke': '21 July 2019',
  '200m breaststroke': '28 July 2023',
  '50m butterfly': '1 July 2018',
  '100m butterfly': '31 July 2021',
  '200m butterfly': '21 June 2022',
  '200m individual medley': '30 July 2025',
  '400m individual medley': '23 July 2023'}}

In [55]:
world_records = {}
world_records["LC Men"] = df.to_dict()["Time"]

world_records

{'LC Men': {'50m freestyle': '20.88',
  '100m freestyle': '46.40',
  '200m freestyle': '1:42.00',
  '400m freestyle': '3:39.96',
  '800m freestyle': '7:32.12',
  '1500m freestyle': '14:26.79',
  '50m backstroke': '23.55',
  '100m backstroke': '51.60',
  '200m backstroke': '1:51.92',
  '50m breaststroke': '25.95',
  '100m breaststroke': '56.88',
  '200m breaststroke': '2:05.48',
  '50m butterfly': '22.27',
  '100m butterfly': '49.45',
  '200m butterfly': '1:50.34',
  '200m individual medley': '1:52.69',
  '400m individual medley': '4:02.50'}}

In [ ]:
TABLE_RECORDS = (0, 1, 3, 4)
COURSES = ("LC Men", "LC Women", "SC Men", "SC Women")
world_records = {}
for table_record, course in zip(TABLE_RECORDS, COURSES):
    df = tables[table_record][["Event", "Time", "Name", "Nationality", "Date"]]
    df = df[~df["Event"].str.contains("relay")]
    df = df.set_index("Event")
    world_records[course] = df.to_dict()["Time"]

world_records

{'LC Men': {'50m freestyle': '20.88',
  '100m freestyle': '46.40',
  '200m freestyle': '1:42.00',
  '400m freestyle': '3:39.96',
  '800m freestyle': '7:32.12',
  '1500m freestyle': '14:26.79',
  '50m backstroke': '23.55',
  '100m backstroke': '51.60',
  '200m backstroke': '1:51.92',
  '50m breaststroke': '25.95',
  '100m breaststroke': '56.88',
  '200m breaststroke': '2:05.48',
  '50m butterfly': '22.27',
  '100m butterfly': '49.45',
  '200m butterfly': '1:50.34',
  '200m individual medley': '1:52.69',
  '400m individual medley': '4:02.50'},
 'LC Women': {'50m freestyle': '23.19',
  '100m freestyle': '51.68',
  '200m freestyle': '1:52.23',
  '400m freestyle': '3:54.18',
  '800m freestyle': '8:04.12',
  '1500m freestyle': '15:20.48',
  '50m backstroke': '26.56',
  '100m backstroke': '57.13',
  '200m backstroke': '2:03.14',
  '50m breaststroke': '29.16',
  '100m breaststroke': '1:04.13',
  '200m breaststroke': '2:17.55',
  '50m butterfly': '24.43',
  '100m butterfly': '54.33',
  '200m butterfly': '2:01.65',
  '200m individual medley': '2:05.70',
  '400m individual medley': '4:23.65'},
 'SC Men': {'50m freestyle': '19.90',
  '100m freestyle': '44.84',
  '200m freestyle': '1:38.61',
  '400m freestyle': '3:32.25',
  '800m freestyle': '7:20.46',
  '1500m freestyle': '14:06.88',
  '50m backstroke': '22.11',
  '100m backstroke': '48.16',
  '200m backstroke': '1:45.12',
  '50m breaststroke': '24.95',
  '100m breaststroke': '55.28',
  '200m breaststroke': '1:59.52',
  '50m butterfly': '21.32',
  '100m butterfly': '47.68',
  '200m butterfly': '1:46.85',
  '100m individual medley': '49.28',
  '200m individual medley': '1:48.88',
  '400m individual medley': '3:54.81'},
 'SC Women': {'50m freestyle': '22.83',
  '100m freestyle': '49.93',
  '200m freestyle': '1:49.36',
  '400m freestyle': '3:50.25',
  '800m freestyle': '7:54.00',
  '1500m freestyle': '15:08.24',
  '50m backstroke': '25.23',
  '100m backstroke': '54.02',
  '200m backstroke': '1:57.33',
  '50m breaststroke': '28.37',
  '100m breaststroke': '1:02.36',
  '200m breaststroke': '2:12.50',
  '50m butterfly': '23.72',
  '100m butterfly': '52.71',
  '200m butterfly': '1:59.32',
  '100m individual medley': '55.11',
  '200m individual medley': '2:01.63',
  '400m individual medley': '4:15.48'}}